= Demo EAP AMQ

Demonstration on how to deploy EAP using s2i and connect to an external AMQ instance.

== Deploying on OpenShift

=== Create the namespace used in the demo
----
oc new-project eap-amq
----

=== Install the AMQ Broker operator

----
oc create -f openshift/operator-group.yml
oc create -f openshift/operator.yml
----

=== Create the AMQ Broker operator resources

Once the operator is running you can provision the broker and the address.

----
oc create -f openshift/broker.yml
oc create -f openshift/address.yml
----

=== Deploy the Application

----
oc process -f openshift/eap74-basic-s2i.yml \
 -p EAP_IMAGE_NAME=jboss-eap74-openjdk11-openshift:7.4.0 \
 -p EAP_RUNTIME_IMAGE_NAME=jboss-eap74-openjdk11-runtime-openshift:7.4.0 \
 -p SOURCE_REPOSITORY_URL="https://github.com/GuilhermeCamposo/demo_eap-amq.git" \
 -p SOURCE_REPOSITORY_REF="main" | oc create -f -
----

=== Testing the Application

Paste the following result in your browser
----
EAP_HOST=$(oc get route eap-app -o jsonpath='{.spec.host}')
echo "http://$EAP_HOST/HelloWorld"
----

Check the applications logs to verify if the MDB is consuming the messages.


== Deploying Local

* Run your EAP instance using the link:https://github.com/GuilhermeCamposo/demo_eap-amq/blob/main/configuration/standalone-openshift.xml[standalone-openshift.yml]. *Don't forget to substitute the host address for your AMQ Broker instance*.

* This Java project is using `wildfly-maven-plugin`. If you have a JBoss EAP running in the same host, you may use it to deploy the application to EAP:

----
mvn clean package wildfly:deploy -Plocal
----
