apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/aws-ebs
    volume.kubernetes.io/selected-node: ip-10-0-137-104.ec2.internal
    volume.kubernetes.io/storage-provisioner: kubernetes.io/aws-ebs
  creationTimestamp: "2022-08-10T15:46:47Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    ActiveMQArtemis: amq
    application: amq-app
    com.company: Red_Hat
    rht.comp: Broker_AMQ
    rht.comp_ver: 7.10.0
    rht.prod_name: Red_Hat_Integration
    rht.prod_ver: 2022.Q2
    rht.subcomp: broker-amq
    rht.subcomp_t: application
  name: amq-amq-ss-0
  namespace: eap-amq
  resourceVersion: "61458"
  uid: b55c9e30-2b9e-4b66-b9b3-e518e8053efb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2
  volumeMode: Filesystem
  volumeName: pvc-b55c9e30-2b9e-4b66-b9b3-e518e8053efb
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  phase: Bound
