apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2022-08-10T15:46:47Z"
    labels:
      ActiveMQArtemis: amq
      application: amq-app
      com.company: Red_Hat
      rht.comp: Broker_AMQ
      rht.comp_ver: 7.10.0
      rht.prod_name: Red_Hat_Integration
      rht.prod_ver: 2022.Q2
      rht.subcomp: broker-amq
      rht.subcomp_t: application
    name: amq-amqp-0-svc
    namespace: eap-amq
    ownerReferences:
    - apiVersion: broker.amq.io/v1beta1
      blockOwnerDeletion: true
      controller: true
      kind: ActiveMQArtemis
      name: amq
      uid: d50171b4-5d6c-437c-aece-9c6b449158d9
    resourceVersion: "61359"
    uid: e15100ee-5da2-494f-941a-f0950b75b3d8
  spec:
    clusterIP: 172.30.126.180
    clusterIPs:
    - 172.30.126.180
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: amqp-0
      port: 5672
      protocol: TCP
      targetPort: 5672
    publishNotReadyAddresses: true
    selector:
      ActiveMQArtemis: amq
      application: amq-app
      com.company: Red_Hat
      rht.comp: Broker_AMQ
      rht.comp_ver: 7.10.0
      rht.prod_name: Red_Hat_Integration
      rht.prod_ver: 2022.Q2
      rht.subcomp: broker-amq
      rht.subcomp_t: application
      statefulset.kubernetes.io/pod-name: amq-ss-0
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2022-08-10T15:46:47Z"
    labels:
      ActiveMQArtemis: amq
      application: amq-app
      com.company: Red_Hat
      rht.comp: Broker_AMQ
      rht.comp_ver: 7.10.0
      rht.prod_name: Red_Hat_Integration
      rht.prod_ver: 2022.Q2
      rht.subcomp: broker-amq
      rht.subcomp_t: application
    name: amq-core-0-svc
    namespace: eap-amq
    ownerReferences:
    - apiVersion: broker.amq.io/v1beta1
      blockOwnerDeletion: true
      controller: true
      kind: ActiveMQArtemis
      name: amq
      uid: d50171b4-5d6c-437c-aece-9c6b449158d9
    resourceVersion: "61368"
    uid: f217441e-a7f7-4580-958e-5097433e425e
  spec:
    clusterIP: 172.30.34.21
    clusterIPs:
    - 172.30.34.21
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: core-0
      port: 61616
      protocol: TCP
      targetPort: 61616
    publishNotReadyAddresses: true
    selector:
      ActiveMQArtemis: amq
      application: amq-app
      com.company: Red_Hat
      rht.comp: Broker_AMQ
      rht.comp_ver: 7.10.0
      rht.prod_name: Red_Hat_Integration
      rht.prod_ver: 2022.Q2
      rht.subcomp: broker-amq
      rht.subcomp_t: application
      statefulset.kubernetes.io/pod-name: amq-ss-0
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2022-08-10T15:46:47Z"
    labels:
      ActiveMQArtemis: amq
      application: amq-app
      com.company: Red_Hat
      rht.comp: Broker_AMQ
      rht.comp_ver: 7.10.0
      rht.prod_name: Red_Hat_Integration
      rht.prod_ver: 2022.Q2
      rht.subcomp: broker-amq
      rht.subcomp_t: application
    name: amq-hdls-svc
    namespace: eap-amq
    ownerReferences:
    - apiVersion: broker.amq.io/v1beta1
      blockOwnerDeletion: true
      controller: true
      kind: ActiveMQArtemis
      name: amq
      uid: d50171b4-5d6c-437c-aece-9c6b449158d9
    resourceVersion: "61356"
    uid: 9a8b1ba7-74f1-408f-9ba8-3bd4669f8ecb
  spec:
    clusterIP: None
    clusterIPs:
    - None
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: console-jolokia
      port: 8161
      protocol: TCP
      targetPort: 8161
    - name: all
      port: 61616
      protocol: TCP
      targetPort: 61616
    publishNotReadyAddresses: true
    selector:
      ActiveMQArtemis: amq
      application: amq-app
      com.company: Red_Hat
      rht.comp: Broker_AMQ
      rht.comp_ver: 7.10.0
      rht.prod_name: Red_Hat_Integration
      rht.prod_ver: 2022.Q2
      rht.subcomp: broker-amq
      rht.subcomp_t: application
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2022-08-10T15:46:47Z"
    labels:
      ActiveMQArtemis: amq
      application: amq-app
      com.company: Red_Hat
      rht.comp: Broker_AMQ
      rht.comp_ver: 7.10.0
      rht.prod_name: Red_Hat_Integration
      rht.prod_ver: 2022.Q2
      rht.subcomp: broker-amq
      rht.subcomp_t: application
    name: amq-ping-svc
    namespace: eap-amq
    ownerReferences:
    - apiVersion: broker.amq.io/v1beta1
      blockOwnerDeletion: true
      controller: true
      kind: ActiveMQArtemis
      name: amq
      uid: d50171b4-5d6c-437c-aece-9c6b449158d9
    resourceVersion: "61355"
    uid: c00bf323-8ffd-4473-a964-653f12df3049
  spec:
    clusterIP: None
    clusterIPs:
    - None
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 8888
      protocol: TCP
      targetPort: 8888
    publishNotReadyAddresses: true
    selector:
      ActiveMQArtemis: amq
      application: amq-app
      com.company: Red_Hat
      rht.comp: Broker_AMQ
      rht.comp_ver: 7.10.0
      rht.prod_name: Red_Hat_Integration
      rht.prod_ver: 2022.Q2
      rht.subcomp: broker-amq
      rht.subcomp_t: application
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2022-08-10T15:46:47Z"
    labels:
      ActiveMQArtemis: amq
      application: amq-app
      com.company: Red_Hat
      rht.comp: Broker_AMQ
      rht.comp_ver: 7.10.0
      rht.prod_name: Red_Hat_Integration
      rht.prod_ver: 2022.Q2
      rht.subcomp: broker-amq
      rht.subcomp_t: application
    name: amq-wconsj-0-svc
    namespace: eap-amq
    ownerReferences:
    - apiVersion: broker.amq.io/v1beta1
      blockOwnerDeletion: true
      controller: true
      kind: ActiveMQArtemis
      name: amq
      uid: d50171b4-5d6c-437c-aece-9c6b449158d9
    resourceVersion: "61375"
    uid: 7c2829e5-1466-4dd5-8f59-8afaf9e1ecea
  spec:
    clusterIP: 172.30.209.52
    clusterIPs:
    - 172.30.209.52
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: wconsj-0
      port: 8161
      protocol: TCP
      targetPort: 8161
    publishNotReadyAddresses: true
    selector:
      ActiveMQArtemis: amq
      application: amq-app
      com.company: Red_Hat
      rht.comp: Broker_AMQ
      rht.comp_ver: 7.10.0
      rht.prod_name: Red_Hat_Integration
      rht.prod_ver: 2022.Q2
      rht.subcomp: broker-amq
      rht.subcomp_t: application
      statefulset.kubernetes.io/pod-name: amq-ss-0
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
